# Change these first
owner: ville-ge # Your GitHub organization or username, where this repository lives
repo: dsic-upptime # The name of this repository

sites:
  - name: Geneve.ch
    url: https://www.geneve.ch/fr
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: MEG
    url: https://www.meg.ch/fr
  - name: CJBG
    url: https://www.cjbg.ch/fr
  - name: FMAC
    url: https://www.fmac-geneve.ch/fr
  - name: MAH
    url: https://www.mahmah.ch/
  - name: Ariana
    url: https://www.musee-ariana.ch/fr
  - name: Ariana - Collections en ligne
    url: https://www.musee-ariana.ch/collections/
  - name: BGE
    url: https://bge-geneve.ch/iconographie/
  - name: Prestations sportives
    url: https://demarches.ville-geneve.ch/prestationssportives/
  - name: Webdeb
    url: https://demarches.ville-geneve.ch/debarras-encombrants/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /dsic-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime DSIC
  introTitle: "Monitoring des sites internet de la ville de Genève."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - obrunau-vdg
  - pauregan-vdg
  - ccettour-vdg
  - django80

workflowSchedule:
  graphs: "15 * * * *"
  responseTime: "0 * * * *"
  staticSite: "30 * * * *"
  summary: "15 * * * *"
  updateTemplate: "15 * * * *"
  updates: "45 * * * *"
  uptime: "*/5 * * * *"
